### ISSUE TITLE
refactor elot-lob to an elisp module

### ISSUE THREAD

**Issue by VladimirAlexiev** [johanwk/elot#2]
elot-lob has a lot of elisp code. That is better represented as an elisp module, not as org embeddings.

**Comment by johanwk** [comment]
I fully agree. I'm thinking that as a start, the functions/definitions in section "elisp functions" could easily be separated out.

Still, it makes sense to have an org-mode document an tangle the elisp to a module, so that it's easy to make comments on the code. I'm not sure whether this should be in a separate org file.

As for the section "org source blocks", it's a little different. Certainly everything _could_ be made into elisp code, but I think there's a lot of convenience/flexibility to be had from making use of org-babel. So my thinking is to not start refactoring right away.

**Comment by johanwk** [comment]
As a small start, the elisp code _except org-babel blocks_ is now in `elot.el`, 5161ba9

**Comment by johanwk** [comment]
as a start, the subdirectory `elot-package` now has the elisp separated from the org-lob.
