### ISSUE TITLE
plantuml installation/invocation

### ISSUE THREAD

**Issue by VladimirAlexiev** [johanwk/elot#6]
(A bit related to #4)
- It's nice that you use `org-plantuml-jar-path`.
  It's defined in a standard file https://github.com/emacs-mirror/emacs/blob/master/lisp/org/ob-plantuml.el
- I wonder whether we need to do this:
```
(require `ob-plantuml)
```
- it's important to add this if the diagrams may include Unicode: `-charset UTF-8`

https://plantuml.com/emacs lists some other options. In particular an interesting way is to use the https://plantuml.com/plantuml server:
  - pro: always has the latest version of plantuml
  - pro: "usually faster than starting a JVM"
  - cons: depends on internet connectivity

**Comment by VladimirAlexiev** [comment]
I have this in my dot-emacs
```elisp
(eval-after-load "ob-plantuml"
  ' (progn
      (add-to-list 'org-babel-default-header-args:plantuml
                   '(:cache . "yes"))
      (add-to-list 'org-babel-default-header-args:plantuml
                   ;; http://plantuml.sourceforge.net/unicode.html
                   ;; -config /prog/bin/plantuml.cfg"))
                   '(:cmdline . "-charset UTF-8"))
      (add-to-list 'org-babel-default-header-args:plantuml
                   '(:prologue . "
hide circle
hide empty attributes
hide empty methods"))))
```

**Comment by johanwk** [comment]
The defaults look nice, I've never tried that before. So these would be defaults, but easily overridden with header arguments?  I've found it's useful to have a couple of different config files available -- in named org blocks; not least for rdfpuml use, as graphs tend to grow large and need tweaking. Some alternatives could be added for the tool. I need to get some examples out to show what I mean. Coming up.

**Comment by johanwk** [comment]
Major update with https://github.com/johanwk/elot/issues/34#issuecomment-2030867470, it would be great to do some testing.

**Comment by VladimirAlexiev** [comment]
Should we close this?
- @mhodki do you find the plantuml instructions clear enough? https://github.com/johanwk/elot/blob/main/README.org#install-elot-auxiliaries

@johanwk  
- If you use `org-plantuml-jar-path` then it should say to set it to something like `$HOME/bin/plantuml.jar`? 
- how do you pass `"-charset UTF-8"`?
- You don't like the idea of using the plantuml server?

> coloured circles from IDO

Do you mean this diagram? 
![image](https://github.com/johanwk/elot/assets/536250/ec652fd4-8d28-4638-b787-5b64bf578b40)
I like them!

**Comment by johanwk** [comment]
I like them too! This is why rdfpuml is the best, and a big reason to care about ELOT :)

I put a line in the README where I used the term "home directory" instead of `$HOME`, in an attempt to be less alienating to new users.. also on Windows, it will be `%UserProfile%` or even some other environment variable, cf [here](https://superuser.com/questions/607105/is-the-home-environment-variable-normally-set-in-windows).

I need to check the `charset utf-8`. I've had this before, but recently found that it wasn't needed to make characters go through properly. It really needs a check.

And no, I don't think the PlantUML server is a good _default_, at least. In general, and in line with #45, we should offer a tool that doesn't need to access external resources. This is not quite achievable -- ROBOT, for instance, produces lots of error messages when converting Maintenance to Turtle, since the ontology has imports that are retrieved from the web and found to be not entirely bug-free. But I think we must offer a solution that can be run "locally". Since rdfpuml requires Perl and needs to be installed, to install PlantUML as well isn't much extra effort.

**Comment by johanwk** [comment]
I could mention that both PlantUML and rdfpuml run _much_ faster in WSL (Ubuntu) than in native Windows. There's something like a 10x difference. 10 seconds for making an svg, currently on my fairly old laptop, in Windows. But since these diagrams are not going to be made in very large numbers, I think users (like myself) will put up with it.

**Comment by johanwk** [comment]
Seems like this is ok, closing
